FROM python:3.11
ENV REMOTE $REMOTE
ENV RB_HOST $RB_HOST
ENV RB_PORT $RB_PORT
ENV RB_USER $RB_USER
ENV RB_PASS $RB_PASS
ENV MQTT_BROKER $MQTT_BROKER
ENV MQTT_PORT $MQTT_PORT
ENV MQTT_USERNAME $MQTT_USERNAME
ENV MQTT_PW $MQTT_PW
ENV MQTT_TOPIC $MQTT_TOPIC
ENV PRODUCTION_MODULE $PRODUCTION_MODULE

WORKDIR /robot-picking-seq-opt
COPY ./ ./
RUN python -m pip install --upgrade pip
RUN pip install -r requirements.txt

ENV PYTHONUNBUFFERED=1

ENTRYPOINT python main.py $REMOTE $RB_HOST $RB_PORT $RB_USER $RB_PASS $MQTT_BROKER $MQTT_PORT $MQTT_USERNAME $MQTT_PW
