name: Docker Image CI/CD - Robot Picking Sequence
env:
  DOCKER_IMAGE: robot-picking-seq-opt

on:
  push:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  pull_request:
    branches: [ "main" ]
    paths-ignore:
      - '**/README.md'
      - '*.github/workflows/**'
  workflow_dispatch:

jobs:
  build-and-push-image:
    runs-on: ubuntu-latest
    steps:
    - name: Check out repository
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3
      with:
        driver: docker-container
        buildkitd-config-inline: |
          [registry."ghcr.io"]
            mirrors = ["ghcr.io"]

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v2
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.CI_TOKEN }}

    - name: Build and Push Image with Cache
      uses: docker/build-push-action@v6
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ghcr.io/modapto/${{ env.DOCKER_IMAGE }}:latest
        cache-from: type=gha
        cache-to: type=gha,mode=max

  deploy:
    runs-on: ubuntu-latest
    needs: build-and-push-image
    steps:      
      - name: SSH into VM and Deploy new Image with Docker
        uses: appleboy/ssh-action@v1.2.0
        with:
          host: ${{ secrets.VM_HOST_IP }}
          username:  ${{ secrets.VM_USER }}
          key: ${{ secrets.VM_SSH_KEY }}
          envs: CI_TOKEN,GITHUB_ACTOR,DOCKER_IMAGE
          script: |
            # Fail script on first error
            set -e 
            
            # Login to GitHub Container Registry
            echo "$CI_TOKEN" | docker login ghcr.io -u "$GITHUB_ACTOR" --password-stdin
            
            # Deploy new Image on Dev Environment
            cd /root/modapto/system-deployment/smart-services
            docker compose pull $DOCKER_IMAGE
            docker compose up -d --no-deps $DOCKER_IMAGE
            
            # Remove unused images
            docker image prune -f
            
            # Logout
            docker logout ghcr.io
        env:
          CI_TOKEN: ${{ secrets.CI_TOKEN }}
          GITHUB_ACTOR: ${{ github.actor }}
          DOCKER_IMAGE: ${{ env.DOCKER_IMAGE }}
